# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Applies K-Means algorithm to the given data data.mat
#'
#' \code{applyKMeans} returns the the cluster centroids.
#'
#' @param dataMatrix Dataset of type matrix (List of double) and shape (n x d), where n is the number of observations and d is the dimension of the dataset.
#' @param K The number of clusters.
#' @param maxIter Maximum number of iterations of Kmeans clustering algorithm.
#' @return The centroids of the clusters.
#'
#'   For description of how KMeans clustering algorithm works, please see the following url.
#'   \url{https://en.wikipedia.org/wiki/K-means_clustering}
#' @examples
#' applyKMeans(as.matrix(iris[,-5]), 3, 300)
#' @export
applyKMeans <- function(dataMatrix, K, maxIter) {
    .Call(`_KMeansCPP_applyKMeans`, dataMatrix, K, maxIter)
}

